spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      uri: ${MONGO_URL}

  session:
    jdbc:
      initialize-schema: never
      table-name: SPRING_SESSION
    timeout: 360000  # 세션 만료시간 (초)

oauth2:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_SECRET_KEY}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

server:
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: none
        max-age: 360000

swagger:
  server-url: https://api.aptapt.kro.kr

app:
  client-url: http://localhost:3000 # 테스트를 위해 로컬로 설정
