spring:
  config:
    import:
      - "aws-parameterstore:/"
  application:
    name: auction-api
  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    io.awspring.cloud: DEBUG
    com.amazonaws.util: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env"
