spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-h2.sql
      table-name: SPRING_SESSION
    timeout: 3600  # 세션 만료시간 (초)


oauth2:
  kakao:
    client-id: ${REST_API_KEY}
    client-secret: ${ADMIN_KEY}
    redirect-uri: http://localhost:8080/api/oauth/kakao/callback
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me


server:
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: lax
        max-age: 3600
