name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootjar

      - name: Copy JAR to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "build/libs/auction-api.jar"
          target: "/home/ubuntu"

      - name: Deploy and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # 기존 프로세스 종료
            if pgrep -f "auction-api.jar"; then
              echo "Stopping existing application..."
              pkill -f "auction-api.jar"
              sleep 5
            fi
            
            # 애플리케이션 실행
            echo "Starting application..."
            nohup java -jar /home/ubuntu/auction-api.jar \
            --spring.profiles.active=prod \
            -DAWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} \
            -DAWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }} \
            -DAWS_REGION=ap-northeast-2 \
            > /home/ubuntu/auction-api.log 2>&1 &
            
            # 애플리케이션 시작 대기
            echo "Waiting for application to start..."
            sleep 35
            
            # 상태 확인
            if curl -f http://localhost:8080/actuator/health; then
              echo "Application is healthy"
            else
              echo "Application failed to start"
              tail -n 100 /home/ubuntu/auction-api.log
              exit 1
            fi
            
            # 로그 확인
            echo "Recent application logs:"
            tail -n 100 /home/ubuntu/auction-api.log
